import Head from 'next/head';

import ArchitectureList from '@/components/architecture-list/architecture-list';
import NavMenu from '@/components/nav-menu/nav-menu';
import { CategoriesEnum } from '@/enums/categories.enum';
import { IArchitectureCard } from '@/interfaces/architecture.interface';
import { prisma } from '@/lib/prisma';

interface IProps {
  temples: IArchitectureCard[];
}

export default function Home({ temples }: IProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavMenu />
        <ArchitectureList list={temples} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const temples = await prisma.architectural_landmarks.findMany({
    where: {
      category: {
        name: CategoriesEnum.TEMPLES
      }
    },
    select: {
      id: true,
      name: true,
      main_image: true,
      category: {
        select: {
          name: true
        }
      }
    }
  });

  return {
    props: {
      temples
    }
  };
}
